### ISSUE TITLE
add button to hide in virtual keyboard

### ISSUE THREAD

**Issue by marianpatak** [mntn-dev/kbd#1]
I found your script, and it will usefull to add button direct in keys for close keyboard

**Comment by mntn-dev** [comment]
hi,

i've added an example to the demo files — <strike>[demo-keyboard-btn.htm](https://rawgit.com/mntn-dev/kbd/master/demo-keyboard-btn.htm)</strike>  [demo.htm](https://rawgit.com/mntn-dev/kbd/master/demo.htm)

> inject keyboard-btn (show/hide)

**Comment by mntn-dev** [comment]
as of version 0.5, it's built-in 

`$.kbd({`
`toggle_btn: true`
`//(...)`
`});`

**Comment by marianpatak** [comment]
Thank you very much good job


S pozdravom

Marian Patak

marian@patak.sk
+421 918 410 663

Odoslané z iPhonu

Dňa 9. 5. 2018 o 14:07 užívateľ Benjamin Lips <notifications@github.com> napísal:
